# Generated by Django 5.2.8 on 2025-11-27 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-puplish']},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-puplish'], name='blog_post_puplish_6a975f_idx'),
        ),
    ]
